remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: Marvelous Misadventures in Bioinformatics
author: Anson Twk
description: A blog on some snippets of my work in bioinformatics. Hopefully you find something useful here and avoid stupid mistakes I made.
google_analytics: G-2BJDQVMLHB